# Mapping between work type supported by ORCID and the DSpace common publication's types
annotation = text::annotation
website = interactive resource::website
data-set = dataset
book = text::book
book-chapter = text::book::book part
conference-paper = text::conference output::conference proceedings::conference paper
conference-poster = text::conference output::conference proceedings::conference poster
journal-article = text::periodical::journal::journal article
newspaper-article = text::periodical::journal::newspaper
magazine-article = text::periodical::journal::magazine
lecture-speech = text::lecture
patent = text::patent
report = text::report
book-review = text::review::book review
preprint = text::preprint
technical-documentation = text::technical documentation or standard
working-paper = text::working paper
other = other
