# Mapping between work type supported by ORCID and the DSpace common publication's types
#website = Controlled Vocabulary for Resource Type Genres::interactive resource::website
#data-set = Controlled Vocabulary for Resource Type Genres::dataset
book = text::book
book-chapter = text::book::book part
conference-paper = text::conference object
journal-article = text::periodical::journal
newspaper-article = text::periodical::journal::newspaper
magazine-article = text::periodical::journal::magazine
#patent = Controlled Vocabulary for Resource Type Genres::text::patent
report = text::report
book-review = text::review::book review