# Mapping between DSpace common publication's types and the type supported by ORCID

# English mapping
Resource\ Types\:\:interactive\ resource\:\:website = website
Resource\ Types\:\:dataset = data-set
Resource\ Types\:\:text\:\:annotation = annotation
Resource\ Types\:\:text\:\:book/monograph = book
Resource\ Types\:\:text\:\:book/monograph\:\:book\ part\ or\ chapter = book-chapter
Resource\ Types\:\:text\:\:conference\ object = conference-paper
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ paper\ not\ in\ proceedings = conference-paper
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ poster\ not\ in\ proceedings = conference-poster
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ presentation = conference-paper
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ proceedings = conference-paper
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ proceedings\:\:conference\ paper = conference-paper
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ proceedings\:\:conference\ poster = conference-poster
Resource\ Types\:\:text\:\:journal = journal-article
Resource\ Types\:\:text\:\:journal\:\:editorial = journal-article
Resource\ Types\:\:text\:\:journal\:\:journal\ article = journal-article
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:corrigendum = journal-article
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:data\ paper = journal-article
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:research\ article = journal-article
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:review\ article = journal-article
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:software\ paper = journal-article
Resource\ Types\:\:text\:\:lecture = lecture-speech
Resource\ Types\:\:text\:\:magazine = magazine-article
Resource\ Types\:\:text\:\:newspaper = newspaper-article
Resource\ Types\:\:text\:\:newspaper\:\:newspaper\ article = newspaper-article
Resource\ Types\:\:text\:\:preprint = preprint
Resource\ Types\:\:text\:\:report = report
Resource\ Types\:\:text\:\:report\:\:clinical\ study = report
Resource\ Types\:\:text\:\:report\:\:data\ management\ plan = data-management-plan
Resource\ Types\:\:text\:\:report\:\:memorandum = report
Resource\ Types\:\:text\:\:report\:\:policy\ report = report
Resource\ Types\:\:text\:\:report\:\:project\ deliverable = report
Resource\ Types\:\:text\:\:report\:\:research\ protocol = report
Resource\ Types\:\:text\:\:report\:\:research\ report = report
Resource\ Types\:\:text\:\:report\:\:technical\ report = report
Resource\ Types\:\:text\:\:review = book-review
Resource\ Types\:\:text\:\:review\:\:book\ review = book-review
Resource\ Types\:\:text\:\:review\:\:commentary = book-review
Resource\ Types\:\:text\:\:review\:\:peer\ review = book-review
Resource\ Types\:\:text\:\:technical\ documentation\ or\ standard = technical-standard
Resource\ Types\:\:text\:\:working\ paper = working-paper
Resource\ Types\:\:other = other

interactive\ resource\:\:website = website
dataset = data-set
text\:\:annotation = annotation
text\:\:book/monograph = book
text\:\:book/monograph\:\:book\ part\ or\ chapter = book-chapter
text\:\:conference\ object = conference-paper
text\:\:conference\ object\:\:conference\ paper\ not\ in\ proceedings = conference-paper
text\:\:conference\ object\:\:conference\ poster\ not\ in\ proceedings = conference-poster
text\:\:conference\ output\:\:conference\ presentation = conference-paper
text\:\:conference\ output\:\:conference\ proceedings = conference-paper
text\:\:conference\ output\:\:conference\ proceedings\:\:conference\ paper = conference-paper
text\:\:conference\ output\:\:conference\ proceedings\:\:conference\ poster = conference-poster
text\:\:journal = journal-article
text\:\:journal\:\:editorial = journal-article
text\:\:journal\:\:journal\ article = journal-article
text\:\:journal\:\:journal\ article\:\:corrigendum = journal-article
text\:\:journal\:\:journal\ article\:\:data\ paper = journal-article
text\:\:journal\:\:journal\ article\:\:research\ article = journal-article
text\:\:journal\:\:journal\ article\:\:review\ article = journal-article
text\:\:journal\:\:journal\ article\:\:software\ paper = journal-article
text\:\:lecture = lecture-speech
text\:\:magazine = magazine-article
text\:\:newspaper = newspaper-article
text\:\:newspaper\:\:newspaper\ article = newspaper-article
text\:\:preprint = preprint
text\:\:report = report
text\:\:report\:\:clinical\ study = report
text\:\:report\:\:data\ management\ plan = data-management-plan
text\:\:report\:\:memorandum = report
text\:\:report\:\:policy\ report = report
text\:\:report\:\:project\ deliverable = report
text\:\:report\:\:research\ protocol = report
text\:\:report\:\:research\ report = report
text\:\:report\:\:technical\ report = report
text\:\:review = book-review
text\:\:review\:\:book\ review = book-review
text\:\:review\:\:commentary = book-review
text\:\:review\:\:peer\ review = book-review
text\:\:technical\ documentation\ or\ standard = technical-standard
text\:\:working\ paper = working-paper
other = other


# French mapping
Resource\ Types\:\:ressource\ interactive\:\:website = website
Resource\ Types\:\:Datasets = data-set
Resource\ Types\:\:texte\:\:annotation = annotation
Resource\ Types\:\:texte\:\:ouvrage/monographie = book
Resource\ Types\:\:texte\:\:ouvrage/monographie\:\:chapitre\ de\ livre = book-chapter
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence = conference-paper
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:article\ dans\ une\ conférence\ non\ publié\ dans\ les\ actes = conference-paper
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:poster\ dans\ une\ conférence\ non\ publié\ dans\ les\ actes = conference-poster
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:support\ de\ présentation\ à\ une\ conférence = conference-paper
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence = conference-paper
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence\:\:article\ dans\ une\ conférence/papier\ de\ conférence = conference-paper
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence\:\:poster\ dans\ une\ conférence = conference-poster
Resource\ Types\:\:texte\:\:revue = journal-article
Resource\ Types\:\:texte\:\:revue\:\:éditorial = journal-article
Resource\ Types\:\:texte\:\:revue\:\:article = journal-article
Resource\ Types\:\:texte\:\:revue\:\:article\:\:erratum = journal-article
Resource\ Types\:\:texte\:\:revue\:\:article\:\:data\ paper = journal-article
Resource\ Types\:\:texte\:\:revue\:\:article\:\:article\ scientifique = journal-article
Resource\ Types\:\:texte\:\:revue\:\:article\:\:article\ de\ synthèse = journal-article
Resource\ Types\:\:texte\:\:revue\:\:article\:\:article\ sur\ un\ logiciel = journal-article
Resource\ Types\:\:texte\:\:revue\:\:lettre\ à\ l'éditeur = journal-article
Resource\ Types\:\:texte\:\:cours = lecture-speech
Resource\ Types\:\:texte\:\:magazine = magazine-article
Resource\ Types\:\:texte\:\:journal = newspaper-article
Resource\ Types\:\:texte\:\:journal\:\:article\ de\ journal = newspaper-article
Resource\ Types\:\:texte\:\:Preprint = preprint
Resource\ Types\:\:texte\:\:rapport = report
Resource\ Types\:\:texte\:\:rapport\:\:étude\ clinique = report
Resource\ Types\:\:texte\:\:rapport\:\:plan\ de\ gestion\ de\ données = report
Resource\ Types\:\:texte\:\:rapport\:\:mémo = report
Resource\ Types\:\:texte\:\:rapport\:\:rapport\ stratégique = report
Resource\ Types\:\:texte\:\:rapport\:\:projet\ de\ semetre = report
Resource\ Types\:\:texte\:\:rapport\:\:protocole\ de\ recherche = report
Resource\ Types\:\:texte\:\:rapport\:\:rapport\ de\ recherche = report
Resource\ Types\:\:texte\:\:rapport\:\:rapport\ technique = report
Resource\ Types\:\:texte\:\:synthèse = book-review
Resource\ Types\:\:texte\:\:synthèse\:\:note\ de\ lecture = book-review
Resource\ Types\:\:texte\:\:synthèse\:\:commentaire = book-review
Resource\ Types\:\:texte\:\:synthèse\:\:évaluation\ par\ les\ pairs = book-review
Resource\ Types\:\:texte\:\:manuel\ technique/documentation\ technique = technical-standard
Resource\ Types\:\:texte\:\:working\ paper = working-paper
Resource\ Types\:\:autre = other

ressource\ interactive\:\:website = website
Datasets = data-set
texte\:\:annotation = annotation
texte\:\:ouvrage/monographie = book
texte\:\:ouvrage/monographie\:\:chapitre\ de\ livre = book-chapter
texte\:\:objet\ présenté\ à\ une\ conférence = conference-paper
texte\:\:objet\ présenté\ à\ une\ conférence\:\:article\ dans\ une\ conférence\ non\ publié\ dans\ les\ actes = conference-paper
texte\:\:objet\ présenté\ à\ une\ conférence\:\:poster\ dans\ une\ conférence\ non\ publié\ dans\ les\ actes = conference-poster
texte\:\:objet\ présenté\ à\ une\ conférence\:\:support\ de\ présentation\ à\ une\ conférence = conference-paper
texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence = conference-paper
texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence\:\:article\ dans\ une\ conférence/papier\ de\ conférence = conference-paper
texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence\:\:poster\ dans\ une\ conférence = conference-poster
texte\:\:revue = journal-article
texte\:\:revue\:\:éditorial = journal-article
texte\:\:revue\:\:article = journal-article
texte\:\:revue\:\:article\:\:erratum = journal-article
texte\:\:revue\:\:article\:\:data\ paper = journal-article
texte\:\:revue\:\:article\:\:article\ scientifique = journal-article
texte\:\:revue\:\:article\:\:article\ de\ synthèse = journal-article
texte\:\:revue\:\:article\:\:article\ sur\ un\ logiciel = journal-article
texte\:\:revue\:\:lettre\ à\ l'éditeur = journal-article
texte\:\:cours = lecture-speech
texte\:\:magazine = magazine-article
texte\:\:journal = newspaper-article
texte\:\:journal\:\:article\ de\ journal = newspaper-article
texte\:\:Preprint = preprint
texte\:\:rapport = report
texte\:\:rapport\:\:étude\ clinique = report
texte\:\:rapport\:\:plan\ de\ gestion\ de\ données = report
texte\:\:rapport\:\:mémo = report
texte\:\:rapport\:\:rapport\ stratégique = report
texte\:\:rapport\:\:projet\ de\ semetre = report
texte\:\:rapport\:\:protocole\ de\ recherche = report
texte\:\:rapport\:\:rapport\ de\ recherche = report
texte\:\:rapport\:\:rapport\ technique = report
texte\:\:synthèse = book-review
texte\:\:synthèse\:\:note\ de\ lecture = book-review
texte\:\:synthèse\:\:commentaire = book-review
texte\:\:synthèse\:\:évaluation\ par\ les\ pairs = book-review
texte\:\:manuel\ technique/documentation\ technique = technical-standard
texte\:\:working\ paper = working-paper
autre = other
