# Mapping between DSpace common publication's types and the type supported by ORCID

# English mapping
Resource\ Types\:\:text = http://purl.org/coar/resource_type/c_18cf
Resource\ Types\:\:text\:\:annotation = http://purl.org/coar/resource_type/c_1162
Resource\ Types\:\:text\:\:bibliography = http://purl.org/coar/resource_type/c_86bc
Resource\ Types\:\:text\:\:blog\ post = http://purl.org/coar/resource_type/c_6947
Resource\ Types\:\:text\:\:book/monograph = http://purl.org/coar/resource_type/c_2f33
Resource\ Types\:\:text\:\:book/monograph\:\:book\ part\ or\ chapter = http://purl.org/coar/resource_type/c_3248
Resource\ Types\:\:text\:\:conference\ object = http://purl.org/coar/resource_type/c_c94f
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ paper\ not\ in\ proceedings = http://purl.org/coar/resource_type/c_18cp
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ poster\ not\ in\ proceedings = http://purl.org/coar/resource_type/c_18co
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ presentation = http://purl.org/coar/resource_type/R60J-J5BD
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ proceedings = http://purl.org/coar/resource_type/c_f744
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ proceedings\:\:conference\ paper = http://purl.org/coar/resource_type/c_5794
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ proceedings\:\:conference\ poster = http://purl.org/coar/resource_type/c_6670
Resource\ Types\:\:text\:\:journal = http://purl.org/coar/resource_type/c_0640
Resource\ Types\:\:text\:\:journal\:\:editorial = http://purl.org/coar/resource_type/c_b239
Resource\ Types\:\:text\:\:journal\:\:journal\ article = http://purl.org/coar/resource_type/c_6501
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:corrigendum = http://purl.org/coar/resource_type/c_7acd
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:data\ paper = http://purl.org/coar/resource_type/c_beb9
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:research\ article = http://purl.org/coar/resource_type/c_2df8fbb1
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:review\ article = http://purl.org/coar/resource_type/c_dcae04bc
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:software\ paper = http://purl.org/coar/resource_type/c_7bab
Resource\ Types\:\:text\:\:lecture = http://purl.org/coar/resource_type/c_8544
Resource\ Types\:\:text\:\:letter = http://purl.org/coar/resource_type/c_0857
Resource\ Types\:\:text\:\:magazine = http://purl.org/coar/resource_type/c_2cd9
Resource\ Types\:\:text\:\:manuscript = http://purl.org/coar/resource_type/c_0040
Resource\ Types\:\:text\:\:newspaper = http://purl.org/coar/resource_type/c_2fe3
Resource\ Types\:\:text\:\:newspaper\:\:newspaper\ article = http://purl.org/coar/resource_type/c_998f
Resource\ Types\:\:text\:\:other\ periodical = http://purl.org/coar/resource_type/QX5C-AR31
Resource\ Types\:\:text\:\:preprint = http://purl.org/coar/resource_type/c_816b
Resource\ Types\:\:text\:\:report = http://purl.org/coar/resource_type/c_93fc
Resource\ Types\:\:text\:\:report\:\:clinical\ study = http://purl.org/coar/resource_type/c_7877
Resource\ Types\:\:text\:\:report\:\:data\ management\ plan = http://purl.org/coar/resource_type/c_ab20
Resource\ Types\:\:text\:\:report\:\:memorandum = http://purl.org/coar/resource_type/c_18wz
Resource\ Types\:\:text\:\:report\:\:policy\ report = http://purl.org/coar/resource_type/c_186u
Resource\ Types\:\:text\:\:report\:\:project\ deliverable = http://purl.org/coar/resource_type/c_18op
Resource\ Types\:\:text\:\:report\:\:research\ protocol = http://purl.org/coar/resource_type/YZ1N-ZFT9
Resource\ Types\:\:text\:\:report\:\:research\ report = http://purl.org/coar/resource_type/c_18ws
Resource\ Types\:\:text\:\:report\:\:technical\ report = http://purl.org/coar/resource_type/c_18gh
Resource\ Types\:\:text\:\:research\ proposal = http://purl.org/coar/resource_type/c_baaf
Resource\ Types\:\:text\:\:review = http://purl.org/coar/resource_type/c_efa0
Resource\ Types\:\:text\:\:review\:\:book\ review = http://purl.org/coar/resource_type/c_ba08
Resource\ Types\:\:text\:\:review\:\:commentary = http://purl.org/coar/resource_type/D97F-VB57
Resource\ Types\:\:text\:\:review\:\:peer\ review = http://purl.org/coar/resource_type/H9BQ-739P
Resource\ Types\:\:text\:\:technical\ documentation\ or\ standard = http://purl.org/coar/resource_type/c_71bd
Resource\ Types\:\:text\:\:thesis = http://purl.org/coar/resource_type/c_46ec
Resource\ Types\:\:text\:\:thesis\:\:bachelor\ thesis = http://purl.org/coar/resource_type/c_7a1f
Resource\ Types\:\:text\:\:thesis\:\:doctoral\ thesis = http://purl.org/coar/resource_type/c_db06
Resource\ Types\:\:text\:\:thesis\:\:master\ thesis = http://purl.org/coar/resource_type/c_bdcc
Resource\ Types\:\:text\:\:transcription = http://purl.org/coar/resource_type/6NC7-GK9S
Resource\ Types\:\:text\:\:working\ paper = http://purl.org/coar/resource_type/c_8042

Resource\ Types\:\:other= = http://purl.org/coar/resource_type/c_1843


# French mapping
Resource\ Types\:\:texte = http://purl.org/coar/resource_type/c_18cf
Resource\ Types\:\:texte\:\:annotation = http://purl.org/coar/resource_type/c_1162
Resource\ Types\:\:texte\:\:bibliographie = http://purl.org/coar/resource_type/c_86bc
Resource\ Types\:\:texte\:\:article\ de\ blog = http://purl.org/coar/resource_type/c_6947
Resource\ Types\:\:texte\:\:ouvrage/monographie = http://purl.org/coar/resource_type/c_2f33
Resource\ Types\:\:texte\:\:ouvrage/monographie\:\:chapitre\ de\ livre = http://purl.org/coar/resource_type/c_3248
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence = http://purl.org/coar/resource_type/c_c94f
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:article\ dans\ une\ conférence\ non\ publié\ dans\ les\ actes = http://purl.org/coar/resource_type/c_18cp
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:poster\ dans\ une\ conférence\ non\ publié\ dans\ les\ actes = http://purl.org/coar/resource_type/c_18co
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:support\ de\ présentation\ à\ une\ conférence = http://purl.org/coar/resource_type/R60J-J5BD
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence = http://purl.org/coar/resource_type/c_f744
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence\:\:article\ dans\ une\ conférence/papier\ de\ conférence = http://purl.org/coar/resource_type/c_5794
Resource\ Types\:\:texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence\:\:poster\ dans\ une\ conférence = http://purl.org/coar/resource_type/c_6670
Resource\ Types\:\:texte\:\:revue = http://purl.org/coar/resource_type/c_0640
Resource\ Types\:\:texte\:\:revue\:\:éditorial = http://purl.org/coar/resource_type/c_b239
Resource\ Types\:\:texte\:\:revue\:\:article = http://purl.org/coar/resource_type/c_6501
Resource\ Types\:\:texte\:\:revue\:\:article\:\:erratum = http://purl.org/coar/resource_type/c_7acd
Resource\ Types\:\:texte\:\:revue\:\:article\:\:data\ paper = http://purl.org/coar/resource_type/c_beb9
Resource\ Types\:\:texte\:\:revue\:\:article\:\:article\ scientifique = http://purl.org/coar/resource_type/c_2df8fbb1
Resource\ Types\:\:texte\:\:revue\:\:article\:\:article\ de\ synthèse = http://purl.org/coar/resource_type/c_dcae04bc
Resource\ Types\:\:texte\:\:revue\:\:article\:\:article\ sur\ un\ logiciel = http://purl.org/coar/resource_type/c_7bab
Resource\ Types\:\:texte\:\:revue\:\:lettre\ à\ l'éditeur = http://purl.org/coar/resource_type/c_545b
Resource\ Types\:\:texte\:\:cours = http://purl.org/coar/resource_type/c_8544
Resource\ Types\:\:texte\:\:lettre = http://purl.org/coar/resource_type/c_0857
Resource\ Types\:\:texte\:\:magazine = http://purl.org/coar/resource_type/c_2cd9
Resource\ Types\:\:texte\:\:manuscrit = http://purl.org/coar/resource_type/c_0040
Resource\ Types\:\:texte\:\:partition = http://purl.org/coar/resource_type/c_18cw
Resource\ Types\:\:texte\:\:journal = http://purl.org/coar/resource_type/c_2fe3
Resource\ Types\:\:texte\:\:journal\:\:article\ de\ journal = http://purl.org/coar/resource_type/c_998f
Resource\ Types\:\:texte\:\:autre\ périodique = http://purl.org/coar/resource_type/QX5C-AR31
Resource\ Types\:\:texte\:\:Preprint = http://purl.org/coar/resource_type/c_816b
Resource\ Types\:\:texte\:\:rapport = http://purl.org/coar/resource_type/c_93fc
Resource\ Types\:\:texte\:\:rapport\:\:étude\ clinique = http://purl.org/coar/resource_type/c_7877
Resource\ Types\:\:texte\:\:rapport\:\:plan\ de\ gestion\ de\ données = http://purl.org/coar/resource_type/c_ab20
Resource\ Types\:\:texte\:\:rapport\:\:mémo = http://purl.org/coar/resource_type/c_18wz
Resource\ Types\:\:texte\:\:rapport\:\:rapport\ stratégique = http://purl.org/coar/resource_type/c_186u
Resource\ Types\:\:texte\:\:rapport\:\:projet\ de\ semetre = http://purl.org/coar/resource_type/c_18op
Resource\ Types\:\:texte\:\:rapport\:\:protocole\ de\ recherche = http://purl.org/coar/resource_type/YZ1N-ZFT9
Resource\ Types\:\:texte\:\:rapport\:\:rapport\ de\ recherche = http://purl.org/coar/resource_type/c_18ws
Resource\ Types\:\:texte\:\:rapport\:\:rapport\ technique = http://purl.org/coar/resource_type/c_18gh
Resource\ Types\:\:texte\:\:projet\ de\ recherche = http://purl.org/coar/resource_type/c_baaf
Resource\ Types\:\:texte\:\:synthèse = http://purl.org/coar/resource_type/c_efa0
Resource\ Types\:\:texte\:\:synthèse\:\:note\ de\ lecture = http://purl.org/coar/resource_type/c_ba08
Resource\ Types\:\:texte\:\:synthèse\:\:commentaire = http://purl.org/coar/resource_type/D97F-VB57
Resource\ Types\:\:texte\:\:synthèse\:\:évaluation\ par\ les\ pairs = http://purl.org/coar/resource_type/H9BQ-739P
Resource\ Types\:\:texte\:\:manuel\ technique/documentation\ technique = http://purl.org/coar/resource_type/c_71bd
Resource\ Types\:\:texte\:\:thèse = http://purl.org/coar/resource_type/c_46ec
Resource\ Types\:\:texte\:\:thèse\:\:mémoire\ de\ stage = http://purl.org/coar/resource_type/c_7a1f
Resource\ Types\:\:texte\:\:thèse\:\:thèse\ de\ doctorat = http://purl.org/coar/resource_type/c_db06
Resource\ Types\:\:texte\:\:thèse\:\:mémoire\ de\ master = http://purl.org/coar/resource_type/c_bdcc
Resource\ Types\:\:texte\:\:transcription = http://purl.org/coar/resource_type/6NC7-GK9S
Resource\ Types\:\:texte\:\:working\ paper = http://purl.org/coar/resource_type/c_8042

Resource\ Types\:\:autre= = http://purl.org/coar/resource_type/c_1843