article-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
article-coar-types\:c_0640 = http://purl.org/coar/resource_type/c_0640
article-coar-types\:c_b239 = http://purl.org/coar/resource_type/c_b239
article-coar-types\:c_6501 = http://purl.org/coar/resource_type/c_6501
article-coar-types\:c_beb9 = http://purl.org/coar/resource_type/c_beb9
article-coar-types\:c_2df8fbb1 = http://purl.org/coar/resource_type/c_2df8fbb1
article-coar-types\:c_dcae04bc = http://purl.org/coar/resource_type/c_efa0
article-coar-types\:c_7bab = http://purl.org/coar/resource_type/c_2df8fbb1
book-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
book-coar-types\:c_2f33 = http://purl.org/coar/resource_type/c_2f33
book-coar-types\:c_3248 http://purl.org/coar/resource_type/c_3248
conference-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
conference-coar-types\:c_c94f = http://purl.org/coar/resource_type/c_c94f 
conference-coar-types\:c_18cp = http://purl.org/coar/resource_type/c_18cp
conference-coar-types\:c_18co = http://purl.org/coar/resource_type/c_18co
conference-coar-types\:R60J-J5BD = http://purl.org/coar/resource_type/c_c94f
conference-coar-types\:c_f744 = http://purl.org/coar/resource_type/c_f744
conference-coar-types\:c_5794 = http://purl.org/coar/resource_type/c_5794
conference-coar-types\:c_6670 = http://purl.org/coar/resource_type/c_6670
conference-coar-types\:c_8544 = http://purl.org/coar/resource_type/c_8544
dataset-coar-types\:c_ddb1 = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:ACF7-8YT9 = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:c_cb28 = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:FXF3-D3G7 = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:AM6W-6QAW = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:63NG-B465 = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:A8F1-NPV9 = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:2H0M-X761 = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:H41Y-FW7B = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:DD58-GFSX = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:FF4C-28RK = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:CQMR-7K63 = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:W2XT-7017 = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:NHD0-W6SY = http://purl.org/coar/resource_type/c_ddb1
dataset-coar-types\:c_5ce6 = http://purl.org/coar/resource_type/c_5ce6
dataset-coar-types\:c_c950 = http://purl.org/coar/resource_type/c_5ce6
dataset-coar-types\:QH80-2R4E = http://purl.org/coar/resource_type/c_5ce6
media-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
media-coar-types\:c_6947 = http://purl.org/coar/resource_type/c_18cf
media-coar-types\:c_2cd9 = http://purl.org/coar/resource_type/c_18cf
media-coar-types\:c_998f = http://purl.org/coar/resource_type/c_18cf
design-coar-types\:542X-3S04 = http://purl.org/coar/resource_type/c_1843
design-coar-types\:JBNF-DYAD = http://purl.org/coar/resource_type/c_1843
design-coar-types\:BW7T-YM2G = http://purl.org/coar/resource_type/c_1843
design-coar-types\:c_c513 = http://purl.org/coar/resource_type/c_c513
design-coar-types\:c_8a7e = http://purl.org/coar/resource_type/c_8a7e
design-coar-types\:c_12ce = http://purl.org/coar/resource_type/c_12ce
design-coar-types\:c_ecc8 = http://purl.org/coar/resource_type/c_ecc8
design-coar-types\:c_e9a0 = http://purl.org/coar/resource_type/c_e9a0
design-coar-types\:c_7ad9 = http://purl.org/coar/resource_type/c_7ad9
patent-coar-types\:c_15cd = http://purl.org/coar/resource_type/c_15cd
patent-coar-types\:SB3Y-W4EH = http://purl.org/coar/resource_type/c_15cd
patent-coar-types\:C53B-JCY5 = http://purl.org/coar/resource_type/c_15cd
patent-coar-types\:Z907-YMBB = http://purl.org/coar/resource_type/c_15cd
patent-coar-types\:GPQ7-G5VE = http://purl.org/coar/resource_type/c_15cd
patent-coar-types\:MW8G-3CR8 = http://purl.org/coar/resource_type/c_15cd
patent-coar-types\:9DKX-KSAF = http://purl.org/coar/resource_type/c_15cd
preprint-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
preprint-coar-types\:c_816b = http://purl.org/coar/resource_type/c_816b
preprint-coar-types\:c_8042 = http://purl.org/coar/resource_type/c_8042
report-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
report-coar-types\:c_93fc = http://purl.org/coar/resource_type/c_93fc
report-coar-types\:c_7877 = http://purl.org/coar/resource_type/c_93fc
report-coar-types\:c_ab20 = http://purl.org/coar/resource_type/c_93fc
report-coar-types\:c_186u = http://purl.org/coar/resource_type/c_186u
report-coar-types\:YZ1N-ZFT9 = http://purl.org/coar/resource_type/c_ba1f
report-coar-types\:c_18ws = http://purl.org/coar/resource_type/c_ba1f
report-coar-types\:c_18gh = http://purl.org/coar/resource_type/c_18gh
report-coar-types\:c_71bd = http://purl.org/coar/resource_type/c_71bd
student-coar-types\:c_46ec = http://purl.org/coar/resource_type/c_46ec
student-coar-types\:c_7a1f = http://purl.org/coar/resource_type/c_7a1f
student-coar-types\:c_bdcc = http://purl.org/coar/resource_type/c_bdcc
student-coar-types\:c_18op = http://purl.org/coar/resource_type/c_18op
teaching-coar-types\:c_e059 = http://purl.org/coar/resource_type/c_1843
thesis-coar-types\:c_46ec = http://purl.org/coar/resource_type/c_46ec
thesis-coar-types\:c_db06 = http://purl.org/coar/resource_type/c_db06

publication-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
publication-coar-types\:c_0640 = http://purl.org/coar/resource_type/c_0640
publication-coar-types\:c_b239 = http://purl.org/coar/resource_type/c_b239
publication-coar-types\:c_6501 = http://purl.org/coar/resource_type/c_6501
publication-coar-types\:c_beb9 = http://purl.org/coar/resource_type/c_beb9
publication-coar-types\:c_2df8fbb1 = http://purl.org/coar/resource_type/c_2df8fbb1
publication-coar-types\:c_dcae04bc = http://purl.org/coar/resource_type/c_efa0
publication-coar-types\:c_7bab = http://purl.org/coar/resource_type/c_2df8fbb1
publication-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
publication-coar-types\:c_2f33 = http://purl.org/coar/resource_type/c_2f33
publication-coar-types\:c_3248 http://purl.org/coar/resource_type/c_3248
publication-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
publication-coar-types\:c_c94f = http://purl.org/coar/resource_type/c_c94f 
publication-coar-types\:c_18cp = http://purl.org/coar/resource_type/c_18cp
publication-coar-types\:c_18co = http://purl.org/coar/resource_type/c_18co
publication-coar-types\:R60J-J5BD = http://purl.org/coar/resource_type/c_c94f
publication-coar-types\:c_f744 = http://purl.org/coar/resource_type/c_f744
publication-coar-types\:c_5794 = http://purl.org/coar/resource_type/c_5794
publication-coar-types\:c_6670 = http://purl.org/coar/resource_type/c_6670
publication-coar-types\:c_8544 = http://purl.org/coar/resource_type/c_8544
product-coar-types\:c_ddb1 = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:ACF7-8YT9 = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:c_cb28 = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:FXF3-D3G7 = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:AM6W-6QAW = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:63NG-B465 = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:A8F1-NPV9 = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:2H0M-X761 = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:H41Y-FW7B = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:DD58-GFSX = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:FF4C-28RK = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:CQMR-7K63 = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:W2XT-7017 = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:NHD0-W6SY = http://purl.org/coar/resource_type/c_ddb1
product-coar-types\:c_5ce6 = http://purl.org/coar/resource_type/c_5ce6
product-coar-types\:c_c950 = http://purl.org/coar/resource_type/c_5ce6
product-coar-types\:QH80-2R4E = http://purl.org/coar/resource_type/c_5ce6
publication-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
publication-coar-types\:c_6947 = http://purl.org/coar/resource_type/c_18cf
publication-coar-types\:c_2cd9 = http://purl.org/coar/resource_type/c_18cf
publication-coar-types\:c_998f = http://purl.org/coar/resource_type/c_18cf
product-coar-types\:542X-3S04 = http://purl.org/coar/resource_type/c_1843
product-coar-types\:JBNF-DYAD = http://purl.org/coar/resource_type/c_1843
product-coar-types\:BW7T-YM2G = http://purl.org/coar/resource_type/c_1843
product-coar-types\:c_c513 = http://purl.org/coar/resource_type/c_c513
product-coar-types\:c_8a7e = http://purl.org/coar/resource_type/c_8a7e
product-coar-types\:c_12ce = http://purl.org/coar/resource_type/c_12ce
product-coar-types\:c_ecc8 = http://purl.org/coar/resource_type/c_ecc8
product-coar-types\:c_e9a0 = http://purl.org/coar/resource_type/c_e9a0
product-coar-types\:c_7ad9 = http://purl.org/coar/resource_type/c_7ad9
publication-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
publication-coar-types\:c_816b = http://purl.org/coar/resource_type/c_816b
publication-coar-types\:c_8042 = http://purl.org/coar/resource_type/c_8042
publication-coar-types\:c_18cf = http://purl.org/coar/resource_type/c_18cf
publication-coar-types\:c_93fc = http://purl.org/coar/resource_type/c_93fc
publication-coar-types\:c_7877 = http://purl.org/coar/resource_type/c_93fc
publication-coar-types\:c_ab20 = http://purl.org/coar/resource_type/c_93fc
publication-coar-types\:c_186u = http://purl.org/coar/resource_type/c_186u
publication-coar-types\:YZ1N-ZFT9 = http://purl.org/coar/resource_type/c_ba1f
publication-coar-types\:c_18ws = http://purl.org/coar/resource_type/c_ba1f
publication-coar-types\:c_18gh = http://purl.org/coar/resource_type/c_18gh
publication-coar-types\:c_71bd = http://purl.org/coar/resource_type/c_71bd
publication-coar-types\:c_46ec = http://purl.org/coar/resource_type/c_46ec
publication-coar-types\:c_7a1f = http://purl.org/coar/resource_type/c_7a1f
publication-coar-types\:c_bdcc = http://purl.org/coar/resource_type/c_bdcc
publication-coar-types\:c_18op = http://purl.org/coar/resource_type/c_18op
publication-coar-types\:c_e059 = http://purl.org/coar/resource_type/c_1843
publication-coar-types\:c_46ec = http://purl.org/coar/resource_type/c_46ec
publication-coar-types\:c_db06 = http://purl.org/coar/resource_type/c_db06
product-coar-types\:c_1843 = http://purl.org/coar/resource_type/c_1843