text = document
texte = document
text\:\:annotation = document
texte\:\:annotation = document
text\:\:bibliography = book
texte\:\:bibliographie = book
text\:\:blog\ post = post-weblog
texte\:\:article\ de\ blog = post-weblog
text\:\:book/monograph = book
texte\:\:ouvrage/monographie = book
text\:\:book/monograph\:\:book\ part\ or\ chapter = chapter
texte\:\:ouvrage/monographie\:\:chapitre\ de\ livre = chapter
text\:\:conference\ output = event
texte\:\:objet\ présenté\ à\ une\ conférence = event
text\:\:conference\ output\:\:conference\ paper\ not\ in\ proceedings = speech
texte\:\:objet\ présenté\ à\ une\ conférence\:\:article\ dans\ une\ conférence\ non\ publié\ dans\ les\ actes = speech
text\:\:conference\ output\:\:conference\ poster\ not\ in\ proceedings = speech
texte\:\:objet\ présenté\ à\ une\ conférence\:\:poster\ dans\ une\ conférence\ non\ publié\ dans\ les\ actes = speech
text\:\:conference\ output\:\:conference\ presentation = speech
texte\:\:objet\ présenté\ à\ une\ conférence\:\:support\ de\ présentation\ à\ une\ conférence = speech
text\:\:conference\ output\:\:conference\ proceedings = book
texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence = book
text\:\:conference\ output\:\:conference\ proceedings\:\:conference\ paper = paper-conference
texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence\:\:article\ dans\ une\ conférence/papier\ de\ conférence = paper-conference
text\:\:conference\ output\:\:conference\ proceedings\:\:conference\ poster = paper-conference
texte\:\:objet\ présenté\ à\ une\ conférence\:\:actes\ de\ conférence\:\:poster\ dans\ une\ conférence = paper-conference
text\:\:journal = periodical
texte\:\:revue = periodical
text\:\:journal\:\:editorial = article-journal
texte\:\:revue\:\:éditorial = article-journal
text\:\:journal\:\:journal\ article = article-journal
texte\:\:revue\:\:article = article-journal
text\:\:journal\:\:journal\ article\:\:corrigendum = article-journal
texte\:\:revue\:\:article\:\:erratum = article-journal
text\:\:journal\:\:journal\ article\:\:data\ paper = article-journal
texte\:\:revue\:\:article\:\:data\ paper = article-journal
text\:\:journal\:\:journal\ article\:\:research\ article = article-journal
texte\:\:revue\:\:article\:\:article\ scientifique = article-journal
text\:\:journal\:\:journal\ article\:\:review\ article = article-journal
texte\:\:revue\:\:article\:\:article\ de\ synthèse = article-journal
text\:\:journal\:\:journal\ article\:\:software\ paper = article-journal
texte\:\:revue\:\:article\:\:article\ sur\ un\ logiciel = article-journal
text\:\:journal\:\:letter\ to\ the\ editor = article-journal
texte\:\:revue\:\:lettre\ à\ l'éditeur = article-journal
text\:\:lecture/talk = speech
texte\:\:cours = speech
text\:\:letter = personal_communication
texte\:\:lettre = personal_communication
text\:\:magazine = article-magazine
texte\:\:magazine = article-magazine
text\:\:manuscript = manuscript
texte\:\:manuscrit = manuscript
text\:\:musical\ notation = musical_score
texte\:\:partition = musical_score
text\:\:newspaper = periodical
texte\:\:journal = periodical
text\:\:newspaper\:\:newspaper\ article = article-newspaper
texte\:\:journal\:\:article\ de\ journal = article-newspaper
text\:\:other\ periodical = periodical
texte\:\:autre\ périodique = periodical
text\:\:preprint = article
texte\:\:preprint = article
text\:\:report = report
texte\:\:rapport = report
text\:\:report\:\:clinical\ study = report
texte\:\:rapport\:\:étude\ clinique = report
text\:\:report\:\:data\ management\ plan = report
texte\:\:rapport\:\:plan\ de\ gestion\ de\ données = report
text\:\:report\:\:memorandum = report
texte\:\:rapport\:\:mémo = report
text\:\:report\:\:policy\ report = report
texte\:\:rapport\:\:rapport\ stratégique = report
text\:\:report\:\:project\ deliverable = report
texte\:\:rapport\:\:projet\ de\ semestre = report
text\:\:report\:\:research\ protocol = report
texte\:\:rapport\:\:protocole\ de\ recherche = report
text\:\:report\:\:research\ report = report
texte\:\:rapport\:\:rapport\ de\ recherche = report
text\:\:report\:\:technical\ report = report
texte\:\:rapport\:\:rapport\ technique = report
text\:\:research\ proposal = document
texte\:\:projet\ de\ recherche = document
text\:\:review = review
texte\:\:synthèse = review
text\:\:review\:\:book\ review = review-book
texte\:\:synthèse\:\:note\ de\ lecture = review-book
text\:\:review\:\:commentary = review
texte\:\:synthèse\:\:commentaire = review
text\:\:review\:\:peer\ review = review
texte\:\:synthèse\:\:évaluation\ par\ les\ pairs = review
text\:\:technical\ documentation\ or\ standard = standard
texte\:\:manuel\ technique/documentation\ technique = standard
text\:\:thesis = thesis
texte\:\:thèse = thesis
text\:\:thesis\:\:bachelor\ thesis = thesis
texte\:\:thèse\:\:mémoire\ de\ stage = thesis
text\:\:thesis\:\:doctoral\ thesis = thesis
texte\:\:thèse\:\:thèse\ de\ doctorat = thesis
text\:\:thesis\:\:master\ thesis = thesis
texte\:\:thèse\:\:mémoire\ de\ master = thesis
text\:\:transcription = document
texte\:\:transcription = document
text\:\:working\ paper = article
texte\:\:working\ paper = article
other = document
autre = document
patent = patent
brevet = patent
patent\:\:PCT\ application = patent
brevet\:\:demande\ PCT = patent
patent\:\:design\ patent = patent
brevet\:\:brevet\ de\ conception = patent
patent\:\:plant\ patent = patent
brevet\:\:brevet\ de\ plante = patent
patent\:\:plant\ variety\ protection = patent
brevet\:\:certificat\ d'obtention\ végétale = patent
patent\:\:software\ patent = patent
brevet\:\:brevet\ de\ logiciel = patent
patent\:\:utility\ model = patent
brevet\:\:modèle\ d'utilité = patent
cartographic\ material = map
matériel\ cartographique = map
cartographic\ material\:\:map = map
matériel\ cartographique\:\:carte\ géographique = map
dataset = dataset
jeu\ de\ données = dataset
dataset\:\:aggregated\ data = dataset
jeu\ de\ données\:\:données\ agrégées = dataset
dataset\:\:clinical\ trial\ data = dataset
jeu\ de\ données\:\:données\ d'essai\ clinique = dataset
dataset\:\:compiled\ data = dataset
jeu\ de\ données\:\:données\ compilées = dataset
dataset\:\:encoded\ data = dataset
jeu\ de\ données\:\:données\ encodées = dataset
dataset\:\:experimental\ data = dataset
jeu\ de\ données\:\:données\ expérimentales = dataset
dataset\:\:genomic\ data = dataset
jeu\ de\ données\:\:données\ génomiques = dataset
dataset\:\:geospatial\ data = dataset
jeu\ de\ données\:\:données\ géospatiales = dataset
dataset\:\:laboratory\ notebook = dataset
jeu\ de\ données\:\:carnet\ de\ laboratoire = dataset
dataset\:\:measurement\ and\ test\ data = dataset
jeu\ de\ données\:\:données\ de\ mesure\ et\ d'essai = dataset
dataset\:\:observational\ data = dataset
jeu\ de\ données\:\:données\ d'observation = dataset
dataset\:\:recorded\ data = dataset
jeu\ de\ données\:\:données\ enregistrées = dataset
dataset\:\:simulation\ data = dataset
jeu\ de\ données\:\:données\ de\ simulation = dataset
dataset\:\:survey\ data = dataset
jeu\ de\ données\:\:données\ d'enquête = dataset
design = graphic
schéma = graphic
design\:\:industrial\ design = graphic
schéma\:\:schéma\ industriel = graphic
design\:\:layout\ design = graphic
schéma\:\:schéma\ de\ configuration = graphic
image = figure
#image = figure
image\:\:moving\ image = motion_picture
image\:\:image\ animée = motion_picture
image\:\:moving\ image\:\:video = motion_picture
image\:\:image\ animée\:\:vidéo = motion_picture
image\:\:still\ image = graphic
image\:\:image\ fixe = graphic
interactive\ resource = webpage
ressource\ interactive = webpage
interactive\ resource\:\:website = webpage
ressource\ interactive\:\:site\ web = webpage
Teaching\ material = document
ressource\ pédagogique\ ou\ d'enseignement = document
software = software
logiciel = software
software\:\:research\ software = software
logiciel\:\:logiciel\ de\ recherche = software
software\:\:source\ code = software
logiciel\:\:code\ source = software
sound = song
son = song
sound\:\:musical\ composition = song
son\:\:composition\ musicale = song
trademark = patent
marque\ déposée = patent
workflow = document
#workflow = document
thesis = thesis
thèses = thesis
thesis\:\:doctoral\ thesis = thesis
thèses\:\:thèse\ de\ doctorat = thesis
student\ work = thesis
projet\ étudiant = thesis
student\ work\:\:doctoral\ thesis = thesis
projet\ étudiant\:\:thèse\ de\ doctorat = thesis
student\ work\:\:bachelor\ thesis = thesis
projet\ étudiant\:\:mémoire\ de\ bachelor = thesis
student\ work\:\:master\ thesis = thesis
projet\ étudiant\:\:mémoire\ de\ master = thesis
student\ work\:\:semester\ or\ other\ student\ projects = document
projet\ étudiant\:\:projet\ de\ semestre\ ou\ autres\ projets\ d'étudiants = document
teaching\ material = article
matériel\ pédagogique = article
text\:\:newspaper\ article = article-newspaper
texte\:\:article\ de\ presse = article-newspaper