article-coar-types\:c_18cf = literature
article-coar-types\:c_0640 = literature
article-coar-types\:c_b239 = literature
article-coar-types\:c_6501 = literature
article-coar-types\:c_beb9 = literature
article-coar-types\:c_2df8fbb1 = literature
article-coar-types\:c_dcae04bc = literature
article-coar-types\:c_7bab = literature
book-coar-types\:c_18cf = literature
book-coar-types\:c_2f33 = literature
book-coar-types\:c_3248 = literature
conference-coar-types\:c_18cf = literature
conference-coar-types\:c_c94f = literature 
conference-coar-types\:c_18cp = literature
conference-coar-types\:c_18co = literature
conference-coar-types\:R60J-J5BD = literature
conference-coar-types\:c_f744 = literature
conference-coar-types\:c_5794 = literature
conference-coar-types\:c_6670 = literature
conference-coar-types\:c_8544 = literature
dataset-coar-types\:c_ddb1 = dataset
dataset-coar-types\:ACF7-8YT9 = dataset
dataset-coar-types\:c_cb28 = dataset
dataset-coar-types\:FXF3-D3G7 = dataset
dataset-coar-types\:AM6W-6QAW = dataset
dataset-coar-types\:63NG-B465 = dataset
dataset-coar-types\:A8F1-NPV9 = dataset
dataset-coar-types\:2H0M-X761 = dataset
dataset-coar-types\:H41Y-FW7B = dataset
dataset-coar-types\:DD58-GFSX = dataset
dataset-coar-types\:FF4C-28RK = dataset
dataset-coar-types\:CQMR-7K63 = dataset
dataset-coar-types\:W2XT-7017 = dataset
dataset-coar-types\:NHD0-W6SY = dataset
dataset-coar-types\:c_5ce6 = software
dataset-coar-types\:c_c950 = software
dataset-coar-types\:QH80-2R4E = software
media-coar-types\:c_18cf = literature
media-coar-types\:c_6947 = literature
media-coar-types\:c_2cd9 = literature
media-coar-types\:c_998f = literature
design-coar-types\:542X-3S04 = other research product
design-coar-types\:JBNF-DYAD = other research product
design-coar-types\:BW7T-YM2G = other research product
design-coar-types\:c_c513 = other research product
design-coar-types\:c_8a7e = other research product
design-coar-types\:c_12ce = other research product
design-coar-types\:c_ecc8 = other research product
design-coar-types\:c_e9a0 = other research product
design-coar-types\:c_7ad9 = other research product
patent-coar-types\:c_15cd = literature
patent-coar-types\:SB3Y-W4EH = literature
patent-coar-types\:C53B-JCY5 = literature
patent-coar-types\:Z907-YMBB = literature
patent-coar-types\:GPQ7-G5VE = literature
patent-coar-types\:MW8G-3CR8 = literature
patent-coar-types\:9DKX-KSAF = literature
preprint-coar-types\:c_18cf = literature
preprint-coar-types\:c_816b = literature
preprint-coar-types\:c_8042 = literature
report-coar-types\:c_18cf = literature
report-coar-types\:c_93fc = literature
report-coar-types\:c_7877 = literature
report-coar-types\:c_ab20 = literature
report-coar-types\:c_186u = literature
report-coar-types\:YZ1N-ZFT9 = literature
report-coar-types\:c_18ws = literature
report-coar-types\:c_18gh = literature
report-coar-types\:c_71bd = literature
student-coar-types\:c_46ec = literature
student-coar-types\:c_7a1f = literature
student-coar-types\:c_bdcc = literature
student-coar-types\:c_18op = other research product
teaching-coar-types\:c_e059 = other research product
thesis-coar-types\:c_46ec = literature
thesis-coar-types\:c_db06 = literature

publication-coar-types\:c_18cf = literature
publication-coar-types\:c_0640 = literature
publication-coar-types\:c_b239 = literature
publication-coar-types\:c_6501 = literature
publication-coar-types\:c_beb9 = literature
publication-coar-types\:c_2df8fbb1 = literature
publication-coar-types\:c_dcae04bc = literature
publication-coar-types\:c_7bab = literature
publication-coar-types\:c_18cf = literature
publication-coar-types\:c_2f33 = literature
publication-coar-types\:c_3248 = literature
publication-coar-types\:c_18cf = literature
publication-coar-types\:c_c94f = literature 
publication-coar-types\:c_18cp = literature
publication-coar-types\:c_18co = literature
publication-coar-types\:R60J-J5BD = literature
publication-coar-types\:c_f744 = literature
publication-coar-types\:c_5794 = literature
publication-coar-types\:c_6670 = literature
publication-coar-types\:c_8544 = literature
product-coar-types\:c_ddb1 = dataset
product-coar-types\:ACF7-8YT9 = dataset
product-coar-types\:c_cb28 = dataset
product-coar-types\:FXF3-D3G7 = dataset
product-coar-types\:AM6W-6QAW = dataset
product-coar-types\:63NG-B465 = dataset
product-coar-types\:A8F1-NPV9 = dataset
product-coar-types\:2H0M-X761 = dataset
product-coar-types\:H41Y-FW7B = dataset
product-coar-types\:DD58-GFSX = dataset
product-coar-types\:FF4C-28RK = dataset
product-coar-types\:CQMR-7K63 = dataset
product-coar-types\:W2XT-7017 = dataset
product-coar-types\:NHD0-W6SY = dataset
product-coar-types\:c_5ce6 = software
product-coar-types\:c_c950 = software
product-coar-types\:QH80-2R4E = software
publication-coar-types\:c_18cf = literature
publication-coar-types\:c_6947 = literature
publication-coar-types\:c_2cd9 = literature
publication-coar-types\:c_998f = literature
product-coar-types\:542X-3S04 = other research product
product-coar-types\:JBNF-DYAD = other research product
product-coar-types\:BW7T-YM2G = other research product
product-coar-types\:c_c513 = other research product
product-coar-types\:c_8a7e = other research product
product-coar-types\:c_12ce = other research product
product-coar-types\:c_ecc8 = other research product
product-coar-types\:c_e9a0 = other research product
product-coar-types\:c_7ad9 = other research product
publication-coar-types\:c_18cf = literature
publication-coar-types\:c_816b = literature
publication-coar-types\:c_8042 = literature
publication-coar-types\:c_18cf = literature
publication-coar-types\:c_93fc = literature
publication-coar-types\:c_7877 = literature
publication-coar-types\:c_ab20 = literature
publication-coar-types\:c_186u = literature
publication-coar-types\:YZ1N-ZFT9 = literature
publication-coar-types\:c_18ws = literature
publication-coar-types\:c_18gh = literature
publication-coar-types\:c_71bd = literature
publication-coar-types\:c_46ec = literature
publication-coar-types\:c_7a1f = literature
publication-coar-types\:c_bdcc = literature
publication-coar-types\:c_18op = other research product
publication-coar-types\:c_e059 = other research product
publication-coar-types\:c_46ec = literature
publication-coar-types\:c_db06 = literature
product-coar-types\:c_1843 = other research product