Abbreviations = other
Abstracts = othre
Academic\ Dissertation = other
Account\ Book = text::book/monograph
Adaptive\ Clinical\ Trial = other
Address = other
Advertisement = other
Almanac = other
Anecdotes = other
Animation = other
Annual\ Report = text::report
Aphorisms\ and\ Proverbs = other
Architectural\ Drawing = other
Atlas = other
Autobiography = text
Bibliography = text::bibliography
Biography = text
Blog = text::blog post
Book\ Illustrations = other
Book\ Review = text::review::book review
Bookplate = other
Broadside = other
Calendar = other
Caricature = other
Cartoon = other
Case\ Reports = other
Catalog = other
Catalog,\ Bookseller = other
Catalog,\ Commercial = other
Catalog,\ Drug = other
Catalog,\ Publisher = other
Catalog,\ Union = other
Chart = other
Chronology = other
Classical\ Article = text::journal::journal article
Clinical\ Conference = other
Clinical\ Study = text::report::clinical study
Clinical\ Trial = other
Clinical\ Trial\ Protocol = other
Clinical\ Trial,\ Phase\ I = other
Clinical\ Trial,\ Phase\ II = other
Clinical\ Trial,\ Phase\ III = other
Clinical\ Trial,\ Phase\ IV = other
Clinical\ Trial,\ Veterinary = other
Collected\ Correspondence = other
Collected\ Work = other
Collection = other
Comment = other
Comparative\ Study = other
Congress = other
Consensus\ Development\ Conference = other
Consensus\ Development\ Conference,\ NIH = other
Controlled\ Clinical\ Trial = other
Cookbook = text\:\:book/monograph
Corrected\ and\ Republished\ Article = text::journal::journal article
Database = other
Dataset = other
Diary = other
Dictionary = other
Dictionary,\ Chemical = other
Dictionary,\ Classical = other
Dictionary,\ Dental = other
Dictionary,\ Medical = other
Dictionary,\ Pharmaceutic = other
Dictionary,\ Polyglot = other
Directory = other
Dispensatory = other
Documentaries\ and\ Factual\ Films = other
Drawing = other
Duplicate\ Publication = other
Editorial = text::journal::editorial
Electronic\ Supplementary\ Materials = other
Encyclopedia = other
English\ Abstract = text
Ephemera = other
Equivalence\ Trial = other
Essay = other
Eulogy = other
Evaluation\ Study = other
Expression\ of\ Concern = other
Festschrift = other
Fictional Work
Form = other
Formulary = other
Formulary,\ Dental = other
Formulary,\ Homeopathic = other
Formulary,\ Hospital = other
Funeral\ Sermon = other
Government\ Publication = text
Graphic\ Novel = other
Guidebook = text\:\:book/monograph
Guideline = text
Handbook = text\:\:book/monograph
Herbal = other
Historical\ Article = text::journal::journal article
Incunabula = other
Index = other
Instructional\ Film\ and\ Video = other
Interactive\ Tutorial = other
Interview = text
Introductory\ Journal\ Article = text::journal::journal article
Journal\ Article = text::journal::journal article
Juvenile\ Literature = other
Laboratory\ Manual = other
Lecture = text::lecture
Lecture\ Note = other
Legal\ Case = other
Legislation = other
Letter = text::letter
Manuscript = text::manuscript
Manuscript,\ Medical = other
Map = other
Meeting\ Abstract = other
Meta-Analysis = other
Monograph = other
Movable\ Books = text\:\:book/monograph
Multicenter\ Study = other
News = other
Newspaper\ Article = text::newspaper::newspaper article
Nurses\ Instruction = other
Observational\ Study = other
Observational\ Study,\ Veterinary = other
Outline = other
Overall = other
Patent = other
Patient\ Education\ Handout = other
Periodical = text::other periodical
Periodical\ Index = other
Personal\ Narrative = other
Pharmacopoeia = other
Pharmacopoeia,\ Homeopathic = other
Photograph = other
Phrases = other
Pictorial\ Work = other
Poetry = other
Popular\ Work = other
Portrait = other
Postcard = other
Poster = other
Practice\ Guideline = other
Pragmatic\ Clinical\ Trial = other
Preprint = text::preprint
Price\ List = other
Problems\ and\ Exercises = other
Program = other
Programmed\ Instruction = other
Prospectus = other
Public\ Service\ Announcement = other
Publication\ Components = other
Publication\ Formats = other
Published\ Erratum = other
Randomized\ Controlled\ Trial = other
Randomized\ Controlled\ Trial,\ Veterinary = other
Research\ Support,\ American\ Recovery\ and\ Reinvestment\ Act = other
Research\ Support,\ N.I.H.,\ Extramural = other
Research\ Support,\ N.I.H.,\ Intramural = other
Research\ Support,\ Non-U.S.\ Gov't = other
Research\ Support,\ U.S.\ Gov't,\ Non-P.H.S. = other
Research\ Support,\ U.S.\ Gov't,\ P.H.S. = other
Research\ Support,\ U.S.\ Government = other
Resource\ Guide = other
Retracted\ Publication = text
Retraction\ of\ Publication = other
Review = text::review
Scientific\ Integrity\ Review = other
Sermon =
Statistics = other
Study\ Characteristics = other
Study\ Guide = other
Support\ of\ Research = other
Systematic\ Review = other
Tables = other
Technical\ Report = text::report::technical report
Terminology = other
Textbook = text::book/monograph
Twin\ Study = other
Unedited\ Footage = other
Union\ List = other
Unpublished\ Work = other
Validation\ Study = other
Video-Audio\ Media = other
Web\ Archive = other
Webcast = other
Wit\ and\ Humor = other