Text = text
Book = text\:\:book/monograph
BookChapter = text\:\:book/monograph\:\:book\ part\ or\ chapter
ConferencePaper = text\:\:conference\ output\:\:conference\ paper
ConferenceProceeding = text\:\:conference\ output\:\:conference\ proceedings
Journal = text\:\:journal
JournalArticle = text\:\:journal\:\:journal\ article
DataPaper = text\:\:journal\:\:journal\ article\:\:data\ paper
Dataset = dataset
Preprint = text\:\:preprint
Report = text\:\:report
Dissertation = text\:\:thesis
Other = other
