Annotation = text::annotation
Article	= text::journal::journal article
Audiovisual = interactive resource
Bachelor\ thesis = text::thesis::bachelor thesis
Bioentity = other
Book = text::book/monograph
Clinical\ Trial = text::report::clinical study
Collection = other
Conference\ object = text::conference object
Contribution\ for\ newspaper\ or\ weekly\ magazine = text::newspaper
Data\ Management\ Plan = text::report::data management plan
Data\ Paper = text::journal::journal article::data paper
Dataset = dataset
Doctoral\ thesis = text::thesis::doctoral thesis
Event = text::conference object
External\ research\ report = text::report::research report
Film = image::video
Image = image
InteractiveResource = other
Internal\ report = text::report
Journal = text::journal
Lecture = text::lecture
Master\ thesis = text::thesis::master thesis
Model = design
Newsletter = other
Other\ ORP\ type = other
Other\ dataset\ type = dataset
Other\ literature\ type = text
Other\ software\ type = software
Part\ of\ book\ or\ chapter\ of\ book = text::book/monograph::book part or chapter
Patent = patent
PhysicalObject = design
Preprint = text::preprint
Presentation = text::conference output::conference presentation
Project\ deliverable = text::report::project deliverable
Project\ milestone = other
Project\ proposal = other
Protein = other
Report = text::report
Research = text::research proposal
Research\ Object = other
Review = text::review
Software = software
Software\ Paper = text::journal::journal article::software paper
Sound = other
Thesis = text\:\:thesis
UNKNOWN = text
Virtual\ Appliance = other