Annotation = text::annotation
Article	= text::journal::journal article
Audiovisual = other
Bachelor\ thesis = text::thesis::bachelor thesis
Bioentity = other
Book = text::book/monograph
Clinical\ Trial = text::report::clinical study
Collection = other
Conference\ object = text::conference object
Contribution\ for\ newspaper\ or\ weekly\ magazine = text::newspaper
Data\ Management\ Plan = text::report::data management plan
Data\ Paper = text::journal::journal article::data paper
Dataset = other
Doctoral\ thesis = text::thesis::doctoral thesis
Event = other
External\ research\ report = text::report::research report
Film = other
Image = other
InteractiveResource = other
Internal\ report = text::report::research report
Journal = text::journal
Lecture = text::lecture
Master\ thesis = text::thesis::master thesis
Model = other
Newsletter = other
Other\ ORP\ type = other
Other\ dataset\ type = other
Other\ literature\ type = other
Other\ software\ type = other
Part\ of\ book\ or\ chapter\ of\ book = text::book/monograph::book part or chapter
Patent = other
PhysicalObject = other
Preprint = text::preprint
Presentation = text::conference output::conference presentation
Project\ deliverable = text::report::project deliverable
Project\ milestone = other
Project\ proposal = other
Protein = other
Report = text::report
Research = text::research proposal
Research\ Object = other
Review = text::review
Software = other
Software\ Paper = text::journal::journal article::software paper
Sound = other
Thesis = text\:\:thesis
UNKNOWN = other
Virtual\ Appliance = other