Article = text::journal::journal article::research article
Proceedings\ Paper = text::conference output::conference proceedings::conference paper
Meeting\ Abstract = text::conference output::conference proceedings::conference paper
Review = text::journal::journal article::review article
Editorial\ Material = text::journal::editorial
Book\ Chapter = text::book/monograph::book part or chapter
Book = text::book/monograph
Book\ Review = text
Early\ Access = text::journal::journal article
Letter = text
Correction = text
Note = text
News\ Item = text
Data\ Paper = text::journal::journal article::data paper