book = text::book/monograph
book-chapter = text::book/monograph::book part or chapter
book-part = text::book/monograph::book part or chapter
book-section = text::book/monograph::book part or chapter
book-series = text::book/monograph::book part or chapter
book-set = text::book/monograph
book-track = text::book/monograph
component = other
dataset = text::journal::journal article::data paper
dissertation = text::thesis
edited-book = text::book/monograph
journal = text::journal
journal-article = text::journal::journal article
journal-issue = text::journal::journal article
journal-volume = text::journal
monograph = text::book/monograph
peer-review = text::journal::journal article::data paper
posted-content = text::blog post
proceedings = text::conference output::conference proceedings
proceedings-article = other
reference-book = text::book/monograph
reference-entry = other
report = text::report
report-series = text::report
standard = text::technical documentation or standard
standard-series = text::technical documentation or standard
other = other






