Resource\ Types\:\:interactive\ resource = GEN
Resource\ Types\:\:interactive\ resource\:\:website = WEB
Resource\ Types\:\:dataset = DATA
Resource\ Types\:\:dataset\:\:interview = DATA
Resource\ Types\:\:image = ADVS
Resource\ Types\:\:image\:\:moving\ image = ADVS
Resource\ Types\:\:image\:\:moving\ image\:\:video = ADVS
Resource\ Types\:\:image\:\:still\ image = ADVS
Resource\ Types\:\:other = GEN
Resource\ Types\:\:software = COMP
Resource\ Types\:\:software\:\:research\ software = COMP
Resource\ Types\:\:workflow = GEN
Resource\ Types\:\:cartographic\ material = MAP
Resource\ Types\:\:cartographic\ material\:\:MAP = MAP
Resource\ Types\:\:sound = ADVS
Resource\ Types\:\:sound\:\:musical\ composition = ADVS
Resource\ Types\:\:text = GEN
Resource\ Types\:\:text\:\:annotation = GEN
Resource\ Types\:\:text\:\:bibliography = GEN
Resource\ Types\:\:text\:\:book = BOOK
Resource\ Types\:\:text\:\:book\:\:book\ part = CHAP
Resource\ Types\:\:text\:\:conference\ object = CONF
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ proceedings = CONF
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ proceedings\:\:conference\ paper = CONF
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ proceedings\:\:conference\ poster = CONF
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ paper\ not\ in\ proceedings = GEN
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ poster\ not\ in\ proceedings = GEN
Resource\ Types\:\:text\:\:lecture = GEN
Resource\ Types\:\:text\:\:letter = GEN
Resource\ Types\:\:text\:\:periodical = GEN
Resource\ Types\:\:text\:\:periodical\:\:journal = JFULL
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal = JOUR
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article = JOUR
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:data\ paper = JOUR
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:review\ article = JOUR
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:research\ article = JOUR
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:corrigendum = JOUR
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:software\ paper = JOUR
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:editorial = JOUR
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:letter\ to\ the\ editor = JOUR
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:NEWS = NEWS
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:NEWS\:\:NEWS\ article = NEWS
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:magazine = MGZN
Resource\ Types\:\:text\:\:patent = PAT
Resource\ Types\:\:text\:\:preprint = GEN
Resource\ Types\:\:text\:\:report = RPRT
Resource\ Types\:\:text\:\:report\:\:report\ part = RPRT
Resource\ Types\:\:text\:\:report\:\:internal\ report = RPRT
Resource\ Types\:\:text\:\:report\:\:memorandum = RPRT
Resource\ Types\:\:text\:\:report\:\:other\ type\ of\ report = RPRT
Resource\ Types\:\:text\:\:report\:\:policy\ report = RPRT
Resource\ Types\:\:text\:\:report\:\:project\ deliverable = RPRT
Resource\ Types\:\:text\:\:report\:\:project\ deliverable\:\:data\ management\ plan = RPRT
Resource\ Types\:\:text\:\:report\:\:report\ to\ funding\ agency = RPRT
Resource\ Types\:\:text\:\:report\:\:research\ report = RPRT
Resource\ Types\:\:text\:\:report\:\:technical\ report = RPRT
Resource\ Types\:\:text\:\:research\ proposal = GEN
Resource\ Types\:\:text\:\:review = GEN
Resource\ Types\:\:text\:\:review\:\:book\ review = GEN
Resource\ Types\:\:text\:\:technical\ documentation = GEN
Resource\ Types\:\:text\:\:working\ paper = GEN
Resource\ Types\:\:text\:\:thesis = THES
Resource\ Types\:\:text\:\:thesis\:\:bachelor\ thesis = THES
Resource\ Types\:\:text\:\:thesis\:\:doctoral\ thesis = THES
Resource\ Types\:\:text\:\:thesis\:\:master\ thesis = THES
Resource\ Types\:\:text\:\:musical\ notation = MUSIC
Resource\ Types\:\:text\:\:blog\ post = GEN
Resource\ Types\:\:text\:\:manuscript = GEN
Resource\ Types\:\:learning\ object = GEN
Resource\ Types\:\:clinical\ trial = GEN
Resource\ Types\:\:clinical\ study = GEN