text\:\:journal\:\:editorial = editorial
text\:\:journal\:\:journal\ article = journal article
text\:\:journal\:\:journal\ article\:\:research\ article = research article
text\:\:journal\:\:journal\ article\:\:review\ article = review article
text\:\:preprint = preprint
text\:\:working\ paper = working paper
text\:\:lecture/talk = lecture
text\:\:magazine = magazine
# book
text\:\:book/monograph = book
text\:\:book/monograph\:\:book\ part\ or\ chapter = book chapter
# conference output
text\:\:conference\ output\:\:conference\ paper\ not\ in\ proceedings = conference paper not in proceedings
text\:\:conference\ output\:\:conference\ poster\ not\ in\ proceedings = conference poster not in proceedings
text\:\:conference\ output\:\:conference\ presentation = conference presentation
text\:\:conference\ output\:\:conference\ proceedings = conference proceedings
text\:\:conference\ output\:\:conference\ proceedings\:\:conference\ paper = conference paper
text\:\:conference\ output\:\:conference\ proceedings\:\:conference\ poster = conference poster
# report
text\:\:report\:\:data\ management\ plan = data management plan
text\:\:report = report
text\:\:report\:\:technical\ report = report
text\:\:report\:\:research\ report = research report
text\:\:technical\ documentation\ or\ standard = technical documentation or standard
# thesis
text\:\:thesis\:\:doctoral\ thesis = doctoral thesis
text\:\:thesis\:\:master\ thesis = student work
text\:\:report\:\:project\ deliverable = project deliverable

# patent types
patent = patent
patent\:\:PCT\ application = PCT application
patent\:\:design\ patent = design patent
patent\:\:plant\ patent = plant patent
patent\:\:plant\ variety\ protection = plant variety protection
patent\:\:software\ patent = software patent
patent\:\:utility\ model = utility model

# product types
cartographic\ material\:\:map = map
dataset = dataset
dataset\:\:aggregated\ data = aggregated data
dataset\:\:clinical\ trial\ data = clinical trial data
dataset\:\:compiled\ data = compiled data
dataset\:\:encoded\ data = encoded data
dataset\:\:experimental\ data = experimental data
dataset\:\:genomic\ data = genomic data
dataset\:\:geospatial\ data = geospatial data
dataset\:\:laboratory\ notebook = laboratory notebook
dataset\:\:measurement\ and\ test\ data = measurement and test data
dataset\:\:observational\ data = observational data
dataset\:\:recorded\ data = recorded data
dataset\:\:simulation\ data = simulation data
dataset\:\:survey\ data = survey data
design\:\:industrial\ design = industrial design
design\:\:layout\ design = layout design
image\:\:moving\ image = moving image
image\:\:moving\ image\:\:video = video
image\:\:still\ image = still image
interactive\ resource\:\:website = website
software\:\:research\ software = research software
software\:\:source\ code = source code
sound\:\:musical\ composition = musical composition
other = other