ar = text::journal::journal article
ab = other
bk = text::book/monograph
bz = other
ch = text::book/monograph::book part or chapter
cp = Resource Types::text::conference output::conference proceedings::conference paper
cr = other
ed = text::journal::editorial
er = text::journal::journal article::corrigendum
le = text::letter
no = other
pr = other
re = text::review
sh = other