Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:interactive\ resource = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:interactive\ resource\:\:website = WEB
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:dataset = DATA
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:dataset\:\:interview = DATA
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:image = ADVS
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:image\:\:moving\ image = ADVS
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:image\:\:moving\ image\:\:video = ADVS
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:image\:\:still\ image = ADVS
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:other = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:software = COMP
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:software\:\:research\ software = COMP
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:workflow = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:cartographic\ material = MAP
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:cartographic\ material\:\:MAP = MAP
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:sound = ADVS
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:sound\:\:musical\ composition = ADVS
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:annotation = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:bibliography = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:book = BOOK
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:book\:\:book\ part = CHAP
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:conference\ object = CONF
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:conference\ object\:\:conference\ proceedings = CONF
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:conference\ object\:\:conference\ proceedings\:\:conference\ paper = CONF
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:conference\ object\:\:conference\ proceedings\:\:conference\ poster = CONF
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:conference\ object\:\:conference\ paper\ not\ in\ proceedings = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:conference\ object\:\:conference\ poster\ not\ in\ proceedings = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:lecture = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:letter = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal = JFULL
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal = JOUR
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article = JOUR
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:data\ paper = JOUR
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:review\ article = JOUR
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:research\ article = JOUR
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:corrigendum = JOUR
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:software\ paper = JOUR
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:editorial = JOUR
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:letter\ to\ the\ editor = JOUR
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:NEWS = NEWS
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:NEWS\:\:NEWS\ article = NEWS
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:periodical\:\:journal\:\:magazine = MGZN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:patent = PAT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:preprint = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report\:\:report\ part = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report\:\:internal\ report = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report\:\:memorandum = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report\:\:other\ type\ of\ report = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report\:\:policy\ report = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report\:\:project\ deliverable = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report\:\:project\ deliverable\:\:data\ management\ plan = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report\:\:report\ to\ funding\ agency = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report\:\:research\ report = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:report\:\:technical\ report = RPRT
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:research\ proposal = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:review = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:review\:\:book\ review = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:technical\ documentation = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:working\ paper = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:thesis = THES
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:thesis\:\:bachelor\ thesis = THES
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:thesis\:\:doctoral\ thesis = THES
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:thesis\:\:master\ thesis = THES
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:musical\ notation = MUSIC
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:blog\ post = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:text\:\:manuscript = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:learning\ object = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:clinical\ trial = GEN
Controlled\ Vocabulary\ for\ Resource\ Type\ Genres\:\:clinical\ study = GEN