c_f744 = Conference Proceedings
c_6670 = Conference Poster
R60J-J5BD = Conference Presentation
c_8544 = Lecture
c_db06 = PhD thesis
c_bdcc = Master thesis
c_7a1f = Bachelor thesis
c_46ec = Thesis
c_18op = Student Project
c_beb9 = Data Paper
c_7bab = Software Paper
c_b239 = Editorial
c_545b = Letter to the Editor
c_7acd = Corrigendum
c_2fe3 = Newspaper
c_816b = Preprint
c_8042 = Working Paper
c_18ws = Research Report
c_18gh = Technical Report
c_186u = Policy Report
c_7877 = Clinical Study
c_ab20 = Data Management Plan
YZ1N-ZFT9 = Research Protocol
c_18wz = Memorandum
c_baaf = Research Proposal
ACF7-8YT9 = Aggregated Data
c_cb28 = Clinical Trial Data
FXF3-D3G7 = Compiled Data
AM6W-6QAW = Encoded Data
63NG-B465 = Experimental Data
A8F1-NPV9 = Genomic Data
2H0M-X761 = Geospatial Data
H41Y-FW7B = Laboratory Notebook
DD58-GFSX = Measurement and Test Data
FF4C-28RK = Observational Data
CQMR-7K63 = Recorded Data
W2XT-7017 = Simulation Data
NHD0-W6SY = Survey Data
c_c950 = Research Software
QH80-2R4E = Source Code
SB3Y-W4EH = PCT Application
C53B-JCY5 = Design Patent
Z907-YMBB = Plant Patent
GPQ7-G5VE = Plant Variety Protection
MW8G-3CR8 = Software Patent
9DKX-KSAF = Utility Model
542X-3S04 = Design
JBNF-DYAD = Industrial Design
BW7T-YM2G = Layout Design
c_ecc8 = Still Image
c_12ce = Video
c_e9a0 = Interactive Resource
c_e059 = Teaching Material
D97F-VB57 = Commentary
H9BQ-739P = Peer Review
c_1162 = Annotation
c_86bc = Bibliography
6NC7-GK9S = Transcription
c_0857 = Letter