article-coar-types\:c_18cf = Journal Articles
article-coar-types\:c_0640 = Journal Articles
article-coar-types\:c_b239 = Journal Articles
article-coar-types\:c_6501 = Journal Articles
article-coar-types\:c_beb9 = Journal Articles
article-coar-types\:c_2df8fbb1 = Journal Articles
article-coar-types\:c_dcae04bc = Reviews
article-coar-types\:c_7bab = Journal Articles
book-coar-types\:c_18cf = Books
book-coar-types\:c_2f33 = Books
book-coar-types\:c_3248 = Book Chapters
conference-coar-types\:c_18cf = Conference Papers
conference-coar-types\:c_c94f = Conference Papers
conference-coar-types\:c_18cp = Conference Papers
conference-coar-types\:c_18co = Posters
conference-coar-types\:R60J-J5BD = Talks
conference-coar-types\:c_f744 = Conference Proceedings
conference-coar-types\:c_5794 = Conference Papers
conference-coar-types\:c_6670 = Posters
conference-coar-types\:c_8544 = Talks
dataset-coar-types\:c_ddb1 = Datasets
dataset-coar-types\:ACF7-8YT9 = Datasets
dataset-coar-types\:c_cb28 = Datasets
dataset-coar-types\:FXF3-D3G7 = Datasets
dataset-coar-types\:AM6W-6QAW = Datasets
dataset-coar-types\:63NG-B465 = Datasets
dataset-coar-types\:A8F1-NPV9 = Datasets
dataset-coar-types\:2H0M-X761 = Datasets
dataset-coar-types\:H41Y-FW7B = Datasets
dataset-coar-types\:DD58-GFSX = Datasets
dataset-coar-types\:FF4C-28RK = Datasets
dataset-coar-types\:CQMR-7K63 = Datasets
dataset-coar-types\:W2XT-7017 = Datasets
dataset-coar-types\:NHD0-W6SY = Datasets
dataset-coar-types\:c_5ce6 = Datasets
dataset-coar-types\:c_c950 = Softwares
dataset-coar-types\:QH80-2R4E = Softwares
media-coar-types\:c_18cf = Text
media-coar-types\:c_6947 = Media
media-coar-types\:c_2cd9 = Media
media-coar-types\:c_998f = Media
design-coar-types\:542X-3S04 = Model
design-coar-types\:JBNF-DYAD = Model
design-coar-types\:BW7T-YM2G = Model
design-coar-types\:c_c513 = Media
design-coar-types\:c_8a7e = Media
design-coar-types\:c_12ce = Media
design-coar-types\:c_ecc8 = Media
design-coar-types\:c_e9a0 = Media
design-coar-types\:c_7ad9 = Media
patent-coar-types\:c_15cd = Patents
patent-coar-types\:SB3Y-W4EH = Patents
patent-coar-types\:C53B-JCY5 = Patents
patent-coar-types\:Z907-YMBB = Patents
patent-coar-types\:GPQ7-G5VE = Patents
patent-coar-types\:MW8G-3CR8 = Patents
patent-coar-types\:9DKX-KSAF = Patents
preprint-coar-types\:c_18cf = Working Papers
preprint-coar-types\:c_816b = Working Papers
preprint-coar-types\:c_8042 = Working Papers
report-coar-types\:c_18cf = Reports
report-coar-types\:c_93fc = Reports
report-coar-types\:c_7877 = Reports
report-coar-types\:c_ab20 = Reports
report-coar-types\:c_186u = Reports
report-coar-types\:YZ1N-ZFT9 = Reports
report-coar-types\:c_18ws = Reports
report-coar-types\:c_18gh = Reports
report-coar-types\:c_71bd = Standards
student-coar-types\:c_46ec = Theses
student-coar-types\:c_7a1f = Student Projects
student-coar-types\:c_bdcc = Student Projects
student-coar-types\:c_18op = Student Projects
teaching-coar-types\:c_e059 = Teaching Resources
thesis-coar-types\:c_46ec = Theses
thesis-coar-types\:c_db06 = Theses
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_0640 = Journal Articles
publication-coar-types\:c_b239 = Journal Articles
publication-coar-types\:c_6501 = Journal Articles
publication-coar-types\:c_beb9 = Journal Articles
publication-coar-types\:c_2df8fbb1 = Journal Articles
publication-coar-types\:c_dcae04bc = Reviews
publication-coar-types\:c_7bab = Journal Articles
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_2f33 = Books
publication-coar-types\:c_3248 = Book Chapters
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_c94f = Conference Papers
publication-coar-types\:c_18cp = Conference Papers
publication-coar-types\:c_18co = Posters
publication-coar-types\:R60J-J5BD = Talks
publication-coar-types\:c_f744 = Conference Proceedings
publication-coar-types\:c_5794 = Conference Papers
publication-coar-types\:c_6670 = Posters
publication-coar-types\:c_8544 = Talks
product-coar-types\:c_ddb1 = Datasets
product-coar-types\:ACF7-8YT9 = Datasets
product-coar-types\:c_cb28 = Datasets
product-coar-types\:FXF3-D3G7 = Datasets
product-coar-types\:AM6W-6QAW = Datasets
product-coar-types\:63NG-B465 = Datasets
product-coar-types\:A8F1-NPV9 = Datasets
product-coar-types\:2H0M-X761 = Datasets
product-coar-types\:H41Y-FW7B = Datasets
product-coar-types\:DD58-GFSX = Datasets
product-coar-types\:FF4C-28RK = Datasets
product-coar-types\:CQMR-7K63 = Datasets
product-coar-types\:W2XT-7017 = Datasets
product-coar-types\:NHD0-W6SY = Datasets
product-coar-types\:c_5ce6 = Datasets
product-coar-types\:c_c950 = Softwares
product-coar-types\:QH80-2R4E = Softwares
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_6947 = Media
publication-coar-types\:c_2cd9 = Media
publication-coar-types\:c_998f = Media
product-coar-types\:542X-3S04 = Model
product-coar-types\:JBNF-DYAD = Model
product-coar-types\:BW7T-YM2G = Model
product-coar-types\:c_c513 = Media
product-coar-types\:c_8a7e = Media
product-coar-types\:c_12ce = Media
product-coar-types\:c_ecc8 = Media
product-coar-types\:c_e9a0 = Media
product-coar-types\:c_7ad9 = Media
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_816b = Preprint
publication-coar-types\:c_8042 = Preprint
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_93fc = Reports
publication-coar-types\:c_7877 = Reports
publication-coar-types\:c_ab20 = Reports
publication-coar-types\:c_186u = Reports
publication-coar-types\:YZ1N-ZFT9 = Reports
publication-coar-types\:c_18ws = Reports
publication-coar-types\:c_18gh = Report
publication-coar-types\:c_71bd = Standards
publication-coar-types\:c_46ec = Theses
publication-coar-types\:c_7a1f = Student Projects
publication-coar-types\:c_bdcc = Student Projects
publication-coar-types\:c_18op = Student Projects
publication-coar-types\:c_e059 = Teaching Resources
publication-coar-types\:c_db06 = Theses
publication-coar-types\:c_1843 = Other