ar = text::journal::journal article::research article
ab = text
ip = text::journal::journal article
bk = text::book/monograph
bz = text::magazine
ch = text::book/monograph::book part or chapter	
cp = text::conference output::conference proceedings::conference paper
cr = text::conference output
ed = text::journal::editorial
er = text::journal::journal article::corrigendum
le = text::letter
no = text
pr = text
re = text::journal::journal article::review article
sh = text