article-coar-types\:c_18cf = Text
article-coar-types\:c_0640 = Journal
article-coar-types\:c_b239 = Text
article-coar-types\:c_6501 = JournalArticle
article-coar-types\:c_beb9 = DataPaper
article-coar-types\:c_2df8fbb1 = JournalArticle
article-coar-types\:c_dcae04bc = JournalArticle
article-coar-types\:c_7bab = JournalArticle
book-coar-types\:c_18cf = Text
book-coar-types\:c_2f33 = Book
book-coar-types\:c_3248 = BookChapter
conference-coar-types\:c_18cf = Text
conference-coar-types\:c_c94f = ConferencePaper 
conference-coar-types\:c_18cp = ConferencePaper
conference-coar-types\:c_18co = ConferencePaper
conference-coar-types\:R60J-J5BD = ConferencePaper
conference-coar-types\:c_f744 = ConferenceProceeding
conference-coar-types\:c_5794 = ConferencePaper
conference-coar-types\:c_6670 = ConferencePaper
conference-coar-types\:c_8544 = ConferencePaper
dataset-coar-types\:c_ddb1 = Dataset
dataset-coar-types\:ACF7-8YT9 = Dataset
dataset-coar-types\:c_cb28 = Dataset
dataset-coar-types\:FXF3-D3G7 = Dataset
dataset-coar-types\:AM6W-6QAW = Dataset
dataset-coar-types\:63NG-B465 = Dataset
dataset-coar-types\:A8F1-NPV9 = Dataset
dataset-coar-types\:2H0M-X761 = Dataset
dataset-coar-types\:H41Y-FW7B = ComputationalNotebook
dataset-coar-types\:DD58-GFSX = Dataset
dataset-coar-types\:FF4C-28RK = Dataset
dataset-coar-types\:CQMR-7K63 = Dataset
dataset-coar-types\:W2XT-7017 = Dataset
dataset-coar-types\:NHD0-W6SY = Dataset
dataset-coar-types\:c_5ce6 = Software
dataset-coar-types\:c_c950 = Software
dataset-coar-types\:QH80-2R4E = Software
media-coar-types\:c_18cf = Text
media-coar-types\:c_6947 = Text
media-coar-types\:c_2cd9 = Text
media-coar-types\:c_998f = Text
design-coar-types\:542X-3S04 = Model
design-coar-types\:JBNF-DYAD = Model
design-coar-types\:BW7T-YM2G = Model
design-coar-types\:c_c513 = Image
design-coar-types\:c_8a7e = Audiovisual
design-coar-types\:c_12ce = Audiovisual
design-coar-types\:c_ecc8 = Image
design-coar-types\:c_e9a0 = InteractiveResource
design-coar-types\:c_7ad9 = Other
patent-coar-types\:c_15cd = Text
patent-coar-types\:SB3Y-W4EH = Text
patent-coar-types\:C53B-JCY5 = Text
patent-coar-types\:Z907-YMBB = Text
patent-coar-types\:GPQ7-G5VE = Text
patent-coar-types\:MW8G-3CR8 = Text
patent-coar-types\:9DKX-KSAF = Text
preprint-coar-types\:c_18cf = Text
preprint-coar-types\:c_816b = Preprint
preprint-coar-types\:c_8042 = Preprint
report-coar-types\:c_18cf = Text
report-coar-types\:c_93fc = Report
report-coar-types\:c_7877 = Report
report-coar-types\:c_ab20 = OutputManagementPlan
report-coar-types\:c_186u = Report
report-coar-types\:YZ1N-ZFT9 = Report
report-coar-types\:c_18ws = Report
report-coar-types\:c_18gh = Report
report-coar-types\:c_71bd = Standard
student-coar-types\:c_46ec = Dissertation
student-coar-types\:c_7a1f = Dissertation
student-coar-types\:c_bdcc = Dissertation
student-coar-types\:c_18op = Text
teaching-coar-types\:c_e059 = Text
thesis-coar-types\:c_46ec = Dissertation
thesis-coar-types\:c_db06 = Dissertation

publication-coar-types\:c_18cf = Text
publication-coar-types\:c_0640 = Journal
publication-coar-types\:c_b239 = Text
publication-coar-types\:c_6501 = JournalArticle
publication-coar-types\:c_beb9 = DataPaper
publication-coar-types\:c_2df8fbb1 = JournalArticle
publication-coar-types\:c_dcae04bc = JournalArticle
publication-coar-types\:c_7bab = JournalArticle
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_2f33 = Book
publication-coar-types\:c_3248 = BookChapter
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_c94f = ConferencePaper 
publication-coar-types\:c_18cp = ConferencePaper
publication-coar-types\:c_18co = ConferencePaper
publication-coar-types\:R60J-J5BD = ConferencePaper
publication-coar-types\:c_f744 = ConferenceProceeding
publication-coar-types\:c_5794 = ConferencePaper
publication-coar-types\:c_6670 = ConferencePaper
publication-coar-types\:c_8544 = ConferencePaper
product-coar-types\:c_ddb1 = Dataset
product-coar-types\:ACF7-8YT9 = Dataset
product-coar-types\:c_cb28 = Dataset
product-coar-types\:FXF3-D3G7 = Dataset
product-coar-types\:AM6W-6QAW = Dataset
product-coar-types\:63NG-B465 = Dataset
product-coar-types\:A8F1-NPV9 = Dataset
product-coar-types\:2H0M-X761 = Dataset
product-coar-types\:H41Y-FW7B = ComputationalNotebook
product-coar-types\:DD58-GFSX = Dataset
product-coar-types\:FF4C-28RK = Dataset
product-coar-types\:CQMR-7K63 = Dataset
product-coar-types\:W2XT-7017 = Dataset
product-coar-types\:NHD0-W6SY = Dataset
product-coar-types\:c_5ce6 = Software
product-coar-types\:c_c950 = Software
product-coar-types\:QH80-2R4E = Software
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_6947 = Text
publication-coar-types\:c_2cd9 = Text
publication-coar-types\:c_998f = Text
product-coar-types\:542X-3S04 = Model
product-coar-types\:JBNF-DYAD = Model
product-coar-types\:BW7T-YM2G = Model
product-coar-types\:c_c513 = Image
product-coar-types\:c_8a7e = Audiovisual
product-coar-types\:c_12ce = Audiovisual
product-coar-types\:c_ecc8 = Image
product-coar-types\:c_e9a0 = InteractiveResource
product-coar-types\:c_7ad9 = Other
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_816b = Preprint
publication-coar-types\:c_8042 = Preprint
publication-coar-types\:c_18cf = Text
publication-coar-types\:c_93fc = Report
publication-coar-types\:c_7877 = Report
publication-coar-types\:c_ab20 = OutputManagementPlan
publication-coar-types\:c_186u = Report
publication-coar-types\:YZ1N-ZFT9 = Report
publication-coar-types\:c_18ws = Report
publication-coar-types\:c_18gh = Report
publication-coar-types\:c_71bd = Standard
publication-coar-types\:c_46ec = Dissertation
publication-coar-types\:c_7a1f = Dissertation
publication-coar-types\:c_bdcc = Dissertation
publication-coar-types\:c_18op = Text
publication-coar-types\:c_e059 = Text
publication-coar-types\:c_46ec = Dissertation
publication-coar-types\:c_db06 = Dissertation
product-coar-types\:c_1843 = Other