Open\ Access = http://purl.org/coar/access_right/c_abf2
Embargoed\ Access = http://purl.org/coar/access_right/c_f1cf
Restricted\ Access = http://purl.org/coar/access_right/c_16ec
Metadata\ Only\ Access = http://purl.org/coar/access_right/c_14cb