P1 = patent::plant patent
P2 = patent::plant patent
P3 = patent::plant patent
P4 = patent::plant patent
P9 = patent::plant patent
P = patent::plant patent
A = patent::utility model
A1 = patent::utility model
A2 = patent::utility model
B1 = patent::utility model
B2 = patent::utility model
S = patent::design patent
S1 = patent::design patent

