Resource\ Types\:\:interactive\ resource\:\:website = webpage
Resource\ Types\:\:dataset = dataset
Resource\ Types\:\:dataset\:\:interview = interview
Resource\ Types\:\:image = figure
Resource\ Types\:\:image\:\:moving\ image = motion_picture
Resource\ Types\:\:image\:\:moving\ image\:\:video = motion_picture
Resource\ Types\:\:image\:\:still\ image = figure
Resource\ Types\:\:cartographic\ material = map
Resource\ Types\:\:cartographic\ material\:\:map = map
Resource\ Types\:\:sound = musical_score
Resource\ Types\:\:sound\:\:musical\ composition = musical_score
Resource\ Types\:\:text\:\:book = book
Resource\ Types\:\:text\:\:book\:\:book\ part = chapter
Resource\ Types\:\:text\:\:conference\ object = paper-conference
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ proceedings = paper-conference
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ proceedings\:\:conference\ paper = paper-conference
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ proceedings\:\:conference\ poster = paper-conference
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ paper\ not\ in\ proceedings = paper-conference
Resource\ Types\:\:text\:\:conference\ object\:\:conference\ poster\ not\ in\ proceedings = paper-conference
Resource\ Types\:\:text\:\:periodical\:\:journal = article-journal
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal = article-journal
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article = article-journal
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:data\ paper = article-journal
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:review\ article = article-journal
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:research\ article = article-journal
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:corrigendum = article-journal
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:journal\ article\:\:software\ paper = article-journal
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:editorial = article-journal
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:contribution\ to\ journal\:\:letter\ to\ the\ editor = article-journal
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:newspaper = article-newspaper
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:newspaper\:\:newspaper\ article = article-newspaper
Resource\ Types\:\:text\:\:periodical\:\:journal\:\:magazine = article-journal
Resource\ Types\:\:text\:\:patent = patent
Resource\ Types\:\:text\:\:report = report
Resource\ Types\:\:text\:\:report\:\:report\ part = report
Resource\ Types\:\:text\:\:report\:\:internal\ report = report
Resource\ Types\:\:text\:\:report\:\:memorandum = report
Resource\ Types\:\:text\:\:report\:\:other\ type\ of\ report = report
Resource\ Types\:\:text\:\:report\:\:policy\ report = report
Resource\ Types\:\:text\:\:report\:\:project\ deliverable = report
Resource\ Types\:\:text\:\:report\:\:project\ deliverable\:\:data\ management\ plan = report
Resource\ Types\:\:text\:\:report\:\:report\ to\ funding\ agency = report
Resource\ Types\:\:text\:\:report\:\:research\ report = report
Resource\ Types\:\:text\:\:report\:\:technical\ report = report
Resource\ Types\:\:text\:\:review = review
Resource\ Types\:\:text\:\:review\:\:book\ review = review-book
Resource\ Types\:\:text\:\:thesis = thesis
Resource\ Types\:\:text\:\:thesis\:\:bachelor\ thesis = thesis
Resource\ Types\:\:text\:\:thesis\:\:doctoral\ thesis = thesis
Resource\ Types\:\:text\:\:thesis\:\:master\ thesis = thesis
Resource\ Types\:\:text\:\:musical\ notation = musical_score
Resource\ Types\:\:text\:\:blog\ post = post
Resource\ Types\:\:text\:\:manuscript = manuscript