preprint = http://purl.org/coar/version/c_71e4c1898caa6e32
postprint = http://purl.org/coar/version/c_ab4af688f83e57aa
publisher = http://purl.org/coar/version/c_970fb48d4fbd8a85
SUBMITTED = http://purl.org/coar/version/c_71e4c1898caa6e32
submitted = http://purl.org/coar/version/c_71e4c1898caa6e32
ACCEPTED = http://purl.org/coar/version/c_ab4af688f83e57aa
accepted = http://purl.org/coar/version/c_ab4af688f83e57aa
PUBLISHED = http://purl.org/coar/version/c_970fb48d4fbd8a85
published = http://purl.org/coar/version/c_970fb48d4fbd8a85