Resource\ Types\:\:text = Text
Resource\ Types\:\:text\:\:annotation = Text
Resource\ Types\:\:text\:\:bibliography = Text
Resource\ Types\:\:text\:\:blog\ post = Text
Resource\ Types\:\:text\:\:book/monograph = Book
Resource\ Types\:\:text\:\:book/monograph\:\:book\ part\ or\ chapter = BookChapter
Resource\ Types\:\:text\:\:conference\ output = ConferencePaper
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ paper\ not\ in\ proceedings = ConferencePaper
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ poster\ not\ in\ proceedings = ConferencePaper
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ presentation = ConferenceProceeding
Resource\ Types\:\:text\:\:conference\ output\:\:conference\ proceedings = ConferenceProceeding
Resource\ Types\:\:text\:\:journal = Journal
Resource\ Types\:\:text\:\:journal\:\:editorial = JournalArticle
Resource\ Types\:\:text\:\:journal\:\:journal\ article = JournalArticle
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:corrigendum = JournalArticle
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:data\ paper = DataPaper
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:research\ article = JournalArticle
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:review\ article = JournalArticle
Resource\ Types\:\:text\:\:journal\:\:journal\ article\:\:software\ paper = JournalArticle
Resource\ Types\:\:text\:\:lecture = Text
Resource\ Types\:\:text\:\:letter = Text
Resource\ Types\:\:text\:\:magazine = Text
Resource\ Types\:\:text\:\:manuscript = Text
Resource\ Types\:\:text\:\:newspaper = Text
Resource\ Types\:\:text\:\:newspaper\:\:newspaper\ article = Text
Resource\ Types\:\:text\:\:other\ periodical = Text
Resource\ Types\:\:text\:\:preprint = Preprint
Resource\ Types\:\:text\:\:report = Report
Resource\ Types\:\:text\:\:report\:\:clinical\ study = Report
Resource\ Types\:\:text\:\:report\:\:data\ management\ plan = Report
Resource\ Types\:\:text\:\:report\:\:memorandum = Report
Resource\ Types\:\:text\:\:report\:\:policy\ report = Report
Resource\ Types\:\:text\:\:report\:\:project\ deliverable = Report
Resource\ Types\:\:text\:\:report\:\:research\ protocol = Report
Resource\ Types\:\:text\:\:report\:\:research\ report = Report
Resource\ Types\:\:text\:\:report\:\:technical\ report = Report
Resource\ Types\:\:text\:\:research\ proposal = Text
Resource\ Types\:\:text\:\:review = PeerReview
Resource\ Types\:\:text\:\:review\:\:book\ review = PeerReview
Resource\ Types\:\:text\:\:review\:\:commentary = PeerReview
Resource\ Types\:\:text\:\:review\:\:peer\ review = PeerReview
Resource\ Types\:\:text\:\:technical\ documentation\ or\ standard = Report
Resource\ Types\:\:text\:\:thesis = Dissertation
Resource\ Types\:\:text\:\:thesis\:\:bachelor\ thesis = Dissertation
Resource\ Types\:\:text\:\:thesis\:\:doctoral\ thesis = Dissertation
Resource\ Types\:\:text\:\:thesis\:\:master\ thesis = Dissertation
Resource\ Types\:\:text\:\:transcription = Text
Resource\ Types\:\:text\:\:working\ paper = Text
Resource\ Types\:\:other= = Other


Resource\ Types\:\:cartographic\ material\:\:map = Other
Resource\ Types\:\:dataset = Dataset
Resource\ Types\:\:dataset\:\:interview = Dataset
Resource\ Types\:\:dataset\:\:aggregated\ data = Dataset
Resource\ Types\:\:dataset\:\:clinical\ trial\ data = Dataset
Resource\ Types\:\:dataset\:\:compiled\ data = Dataset
Resource\ Types\:\:dataset\:\:encoded\ data = Dataset
Resource\ Types\:\:dataset\:\:experimental\ data = Dataset
Resource\ Types\:\:dataset\:\:genomic\ data = Dataset
Resource\ Types\:\:dataset\:\:geospatial\ data = Dataset
Resource\ Types\:\:dataset\:\:laboratory\ notebook = Dataset
Resource\ Types\:\:dataset\:\:measurement\ and\ test\ data = Dataset
Resource\ Types\:\:dataset\:\:observational\ data = Dataset
Resource\ Types\:\:dataset\:\:recorded\ data = Dataset
Resource\ Types\:\:dataset\:\:simulation\ data = Dataset
Resource\ Types\:\:dataset\:\:survey\ data = Dataset
Resource\ Types\:\:design = Other
Resource\ Types\:\:design\:\:industrial\ design = Other
Resource\ Types\:\:design\:\:layout\ design = Other
Resource\ Types\:\:image = Image
Resource\ Types\:\:image\:\:moving\ image = Image
Resource\ Types\:\:image\:\:moving\ image\:\:video = Image
Resource\ Types\:\:image\:\:still\ image = Image
Resource\ Types\:\:interactive\ resource = InteractiveResource
Resource\ Types\:\:interactive\ resource\:\:website = InteractiveResource
Resource\ Types\:\:software = Software
Resource\ Types\:\:software\:\:research\ software = Software
Resource\ Types\:\:software\:\:source\ code = Software
Resource\ Types\:\:sound = Sound
Resource\ Types\:\:sound\:\:musical\ composition = Sound
Resource\ Types\:\:trademark = Other
Resource\ Types\:\:trademark\:\:workflow = Other
Resource\ Types\:\:workflow = Workflow


text = Text
text\:\:annotation = Text
text\:\:bibliography = Text
text\:\:blog\ post = Text
text\:\:book/monograph = Book
text\:\:book/monograph\:\:book\ part\ or\ chapter = BookChapter
text\:\:conference\ output = ConferencePaper
text\:\:conference\ output\:\:conference\ paper\ not\ in\ proceedings = ConferencePaper
text\:\:conference\ output\:\:conference\ poster\ not\ in\ proceedings = ConferencePaper
text\:\:conference\ output\:\:conference\ presentation = ConferenceProceeding
text\:\:conference\ output\:\:conference\ proceedings = ConferenceProceeding
text\:\:journal = Journal
text\:\:journal\:\:editorial = JournalArticle
text\:\:journal\:\:journal\ article = JournalArticle
text\:\:journal\:\:journal\ article\:\:corrigendum = JournalArticle
text\:\:journal\:\:journal\ article\:\:data\ paper = DataPaper
text\:\:journal\:\:journal\ article\:\:research\ article = JournalArticle
text\:\:journal\:\:journal\ article\:\:review\ article = JournalArticle
text\:\:journal\:\:journal\ article\:\:software\ paper = JournalArticle
text\:\:lecture = Text
text\:\:letter = Text
text\:\:magazine = Text
text\:\:manuscript = Text
text\:\:newspaper = Text
text\:\:newspaper\:\:newspaper\ article = Text
text\:\:other\ periodical = Text
text\:\:preprint = Preprint
text\:\:report = Report
text\:\:report\:\:clinical\ study = Report
text\:\:report\:\:data\ management\ plan = Report
text\:\:report\:\:memorandum = Report
text\:\:report\:\:policy\ report = Report
text\:\:report\:\:project\ deliverable = Report
text\:\:report\:\:research\ protocol = Report
text\:\:report\:\:research\ report = Report
text\:\:report\:\:technical\ report = Report
text\:\:research\ proposal = Text
text\:\:review = PeerReview
text\:\:review\:\:book\ review = PeerReview
text\:\:review\:\:commentary = PeerReview
text\:\:review\:\:peer\ review = PeerReview
text\:\:technical\ documentation\ or\ standard = Report
text\:\:thesis = Dissertation
text\:\:thesis\:\:bachelor\ thesis = Dissertation
text\:\:thesis\:\:doctoral\ thesis = Dissertation
text\:\:thesis\:\:master\ thesis = Dissertation
text\:\:transcription = Text
text\:\:working\ paper = Text
other= = Other


cartographic\ material\:\:map = Other
dataset = Dataset
dataset\:\:interview = Dataset
dataset\:\:aggregated\ data = Dataset
dataset\:\:clinical\ trial\ data = Dataset
dataset\:\:compiled\ data = Dataset
dataset\:\:encoded\ data = Dataset
dataset\:\:experimental\ data = Dataset
dataset\:\:genomic\ data = Dataset
dataset\:\:geospatial\ data = Dataset
dataset\:\:laboratory\ notebook = Dataset
dataset\:\:measurement\ and\ test\ data = Dataset
dataset\:\:observational\ data = Dataset
dataset\:\:recorded\ data = Dataset
dataset\:\:simulation\ data = Dataset
dataset\:\:survey\ data = Dataset
design = Other
design\:\:industrial\ design = Other
design\:\:layout\ design = Other
image = Image
image\:\:moving\ image = Image
image\:\:moving\ image\:\:video = Image
image\:\:still\ image = Image
interactive\ resource = InteractiveResource
interactive\ resource\:\:website = InteractiveResource
software = Software
software\:\:research\ software = Software
software\:\:source\ code = Software
sound = Sound
sound\:\:musical\ composition = Sound
trademark = Other
trademark\:\:workflow = Other
workflow = Workflow
